### ISSUE TITLE
[Post] New Loongson Official FFmpeg Marks

### ISSUE THREAD

**Issue by windows1089** [loongson-community/micronews#7]
Author: Yifan Chen
Text: 龙芯官方闭源 FFmpeg 版本更新，该版针对 LS3A4000 进行了优化：http://www.loongnix.org/index.php/%E5%AA%92%E4%BD%93%E7%BC%96%E8%A7%A3%E7%A0%81

**Comment by FlyGoat** [comment]
为了满足rss和twitter的要求，一条post仅可包含一条链接。已经更正并重新approve，谢谢。
